services:
  - type: web
    name: athena-store
    env: node
    plan: starter
    branch: main
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start -- -p $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "24"
    healthCheckPath: /
